name: Build and Deploy to Render

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 21

    - name: Build Spring Boot app
      run: ./mvnw clean package -DskipTests

    - name: Log in to Render Docker registry
      run: |
        echo "${{ secrets.RENDER_SERVICE_TOKEN }}" | docker login registry.render.com -u ${{ secrets.RENDER_SERVICE_TOKEN }} --password-stdin

    - name: Build Docker image
      run: docker build -t registry.render.com/<your-service-name>:latest .

    - name: Push Docker image to Render registry
      run: docker push registry.render.com/<your-service-name>:latest

    - name: Trigger Render deploy
      run: |
        curl -X POST \
        -H "Authorization: Bearer ${{ secrets.RENDER_SERVICE_TOKEN }}" \
        -H "Accept: application/json" \
        https://api.render.com/deploy/srv-xxxxxxxx
